### PR TITLE
Initial cut at stylesheet

### PR DESCRIPTION
**Pull request by vanillajonathan**
Imports Photon colors.
Augments elements with style based on the Photon Design System.
Provides classes.

### CODE REVIEW

**Comment by bwinton** [comment]
Hey Jonathan,

there are some people working on some related things, who I think you might want to talk to before putting a ton of work into this… I'll ping them tomorrow and ask them to comment here with their current status and plans.

Thanks!

**Comment by vanillajonathan** [comment]
@bwinton Ping!

**Comment by bwinton** [comment]
(Pinged. We'll see if they reply.)

**Comment by andymikulski** [comment]
Hey @vanillajonathan , I'm currently working on Photon styles for [Ant](https://ant.design/) so I've gotten my hands dirty with some of this stuff already. Fortunately, Ant uses LESS, so there's no real overlap between what I'm working on and what you've got going here! I have a few thoughts, though:


- What is the dev story for this file? If someone were to download just the CSS file, they'd need to manually download the dependencies (`colors.css`) with it as well. I suspect we should investigate setting up a separate subdir and appropriate npm package (`photon-css`?) - @bwinton any thoughts?

- We should have some sort of documentation regarding what classes are available. In the event this file gets really large, it'd be easier for devs to use if they don't need to dig through the various classes. This could live in the above mentioned subdir, too.

- I know `colors.css` exports CSS variables, but the [browser support](http://caniuse.com/#feat=css-variables) is less than stellar outside FF. It may be worth putting together a small build tool to compile a completely "primitive" CSS file with all the variable values replaced, etc. I can imagine a few arguments to have this one way or the other, so I'm open to any thoughts.

- A feature we're working towards for the Ant styles is a [living style/component guide](https://photon-design.neocities.org/components/button/). It may be beneficial to have a similar demo page for the CSS styles - not necessarily as functional, just something to glance at. Up to you.

Great work! I'm really glad this is being put together.

**Comment by vanillajonathan** [comment]
@andymikulski 

The dev story for this file is that I am developing a WebExtension and needed to style the page. Setting `browser_style` to `true` in the `manifest.json` only styles the popup in the toolbar button not any HTML pages loaded in new tabs.

I include the `colors.css` file with my WebExtension. However, I would really like to see the `colors.css` file included with Firefox so that I could do something like `@import "chrome://browser/content/colors.css";`. This would allow all WebExtension developers to import the Photon colors without have to ship the `colors.css` with their WebExtension. Code re-use.
Also would be good if this CSS I am working on here (or something like this) could be part of Firefox so WebExtension developers could just include that and tag up their elements with classes to get them Photon styled.

I chose plain vanilla CSS because because the intention is to use it with WebExtensions not websites, hence I don't have to care about cross-browser support, I only care about Firefox and I know that versions of Firefox that does support WebExtensions also support CSS variables.

Since the intention is for usage within WebExtensions the stylesheet is heavily opinionated and hence directly styles elements rather than providing classes when possible. This makes the stylesheet easier to use, requires less documentation and HTML have less need for classes.

Also it would be nice if pages such as `about:preferences` and `about:addons` used HTML instead of XUL and all shared one common stylesheet which would be a stylesheet that also could be referenced in WebExtension so that the internal Firefox pages and WebExtensions all could have a unified look.

I don't know if anyone within Mozilla is already working on something similar.

Currently this stylesheet is slightly hampered by Firefox not yet supporting the `system-ui` font-family.

Yes, a component guide is a very good idea.

**Comment by vanillajonathan** [comment]
# Documention
This is a style sheet intended for use by WebExtensions.

## Badges
There is a `.badge` class.
```html
<span class="badge">Badge</span>
```

## Buttons
When multiple buttons are present mark the default action with the `.btn-primary` modifier class. For a bigger button add the `.btn-puffy` modifier class. For a smaller button add the `.btn-micro` modifier class.
For a ghost button there is the `.btn-ghost` class.
For wide buttons there is the `.btn-wide` modifier class.
```html
<button id="cancel">Cancel</button>
<button id="ok" class="btn-default">OK</button>
<button class="btn-wide">Wide</button>
```

## Cards
A card is a flexible and extensible content container. Cards can have shadows, the following shadow classes are provided `.shadow-10`, `.shadow-20`, and `.shadow-30`.
```html
<div class="card shadow-10">This is some text within a card block.</div>
<div class="card shadow-20">This is some text within a card block.</div>
<div class="card shadow-30">This is some text within a card block.</div>
```

## Doorhanger
Can be used with the `.doorhanger-menu` class.
```html
<div class="doorhanger doorhanger-menu">
  <a href="#">Sign in to Sync</a>
  <hr />
  <a href="#">New Window</a>
  <a href="#">New Private Window</a>
</div>
```

## Message bars
Message bars are contextual. The following contextual classes are provided: `.messagebar-attention`, `.messagebar-generic`, `.messagebar-success`, `.messagebar-warning`, and `.messagebar-error`.
```html
<div class="messagebar messagebar-generic">This is a generic message.</div>
<div class="messagebar messagebar-attention">This is a attention message.</div>
<div class="messagebar messagebar-success">This is a success message.</div>
<div class="messagebar messagebar-warning">This is a warning message.</div>
<div class="messagebar messagebar-error">This is a error message.</div>
```
For a variant that is at the top of the screen use the the `.messagebar-fixed` modifier class.
```html
<div class="messagebar messagebar-fixed messagebar-warning">This is a warning message.</div>
```

## Sidebar
A sidebar like in `about:preferences` and `about:addons`. Use the `.richlist` class.
```html
<ul class="richlist w-10">
  <li>Get Add-ons</li>
  <li>Extensions</li>
  <li>Themes</li>
  <li>Plugins</li>
  <li>Dictionaries</li>
  <li>Legacy Extensions</li>
</ul>
```

## Table
The `.table-hover` and `.table-striped` modifier classes are available. 

## Tabs
```html
<nav class="tabs">
  <ul>
    <li><a href="#">Link 1</a></li>
    <li class="active"><a href="#">Link 2</a></li>
    <li><a href="#">Link 3</a></li>
  </ul>
</nav>
```

## Text
Format your text with the contextual `.text-success` and `.text-danger` classes.
```html
<p class="text-success">Things are pretty good.</p>
<p class="text-danger">Things are not looking good.</p>
```

## Helper classes
To prevent text selection there is the `.user-select-none` helper class.

**Comment by BojanKogoj** [comment]
@vanillajonathan I really like what you've done here, I hope it gets merged (otherwise make a separate library please).
Just a few suggestions: Instead of using `button`, use classes so we can apply style to `a` as well. Same goes for `input`, in some cases we would like to use `<div contenteditable="true">`. Textarea is missing?

**Comment by vanillajonathan** [comment]
@BojanKogoj Thanks for the feedback! 😃 

Since the style sheet is currently aimed at WebExtensions (not websites), I went for targeting elements instead of classes where possible to create a opinionated style sheet that is easy to use and just needs to be included. This element-targeting approach isn't set in stone though.

By explicitly targeting the `button` element it might discourage non-semantic abuse of the `a` element. Not sure if that is a good enough reason though. It might change the selector to target both the `button` element as well as a `.btn` or `.button` class so that it could be used with the `a` element.

I did not consider elements with the `contenteditable` attribute, good that you brought it up. 👍 
I could write a selector such as `[contenteditable]` to target elements with the attribute, not sure if that would be too opinionated and inflexible though.

Yeah, `textarea` is missing for now due to a combination of it not being covered by the the Photon documentation, it not being used within Firefox, it looks good unstyled, and me haven forgotten about it.

**Comment by vanillajonathan** [comment]
Okay for anyone wondering  what it kind of looks like here is a CodePen.
https://codepen.io/anon/pen/xXQqBo

Note that the Photon Design System so far have not yet covered  tabs, tables or navigation.
Firefox uses some kind of table widget in some places but rather inconsistently for row colors, hover color and row selection color.
Firefox does use tabs in `about:preferences#privacy` -> "View Certificates".

Firefox is currently quite inconsistent both among different parts of itself as well as with Photon. This makes it difficult to create an authoritative style sheet, especially as someone outside Mozilla and the Photon team.

**Comment by aminalhazwani** [comment]
hey @vanillajonathan thanks for such contribution! I have a couple of concerns thou: a CSS stylesheet is not really a design token, it's more an evolution of a collection of tokens. The purpose of this repository is to serve design decisions in a language application agnostic way while this CSS stylesheet is already a step further. So I think that this PR does not belong here, a CSS stylesheet would be more fit as a resource of the Photon Design System website, would you like to move the conversation over there? That said we are super happy to see the tokens support the work of a developer!

Beside the "token or not token" matter we haven't decided the strategy regarding delivering styled components yet (with all the connected questions like methodologies, semantics, technologies) because for the time being we are focusing on delivering these atomic design attributes. Moreover this Stylesheet includes things that are still under draft like cards, buttons, links, message bars and so on.

**Comment by vanillajonathan** [comment]
Thank you very much for your reply @aminalhazwani, yes some time after I opened this pull request I started to to think that this might out of scope for the design tokens repository.

I am not sure which repository (if any existing one) would be the proper one. Also note that this style sheet has its roots in WebExtensions so as of now it is highly opinionated (in that it directly styles elements where possible) and does not aim for cross-browser compatibility (it uses some Mozilla-specific extensions) so it might not be suited for websites. 

I would be willing to move the conversation wherever appropriate. Also to collaboratively develop it with other developers and possibly the Photon Design System team, or hand it over to them.
I don't know where tho.

The Photon Design System as documented on the Photon website is not comprehensive, not much is covered, so yes the stylesheet covers as much as possible of what little is covered so that includes components still under draft.

**Comment by aminalhazwani** [comment]
hey @vanillajonathan, yeah sorry, this is the repo https://github.com/firefoxux/photon. I think we can continue the conversation here otherwise we will miss all the interesting things that have been said here, what do you think @bwinton? 

I think is totally reasonable to have a specific style that is opinionated and has roots in WebExtensions! As I said we haven't decided how to deliver styled components so I would like to ask you a couple of questions that could help us see this through ☺️ 

There are a couple of approaches that we could follow for serving styled components:
- The first is what you are exactly doing. A stylesheet that people can download and use but I have a couple of concerns. I am not a huge fan of copy/paste of snippets of code, it can happen that people leave off or remove things they don’t understand like ARIA attributes, microformats, and similar; You can never change a class name again; You can’t automatically push out changes to components; And you’re duplicating code.
- Another approach would be take advantage of browser styles and build a more solid system that WebExtension developers can access to. This would mean that you could have direct access to a series of components and patterns that include markup, styles, interaction, a11y and more. So you as a author can fully focus on the experience of you extension.
- Or another option would be to provide style components, as npm module or similar, that authors can install and import based on their needs. 

Keeping all of these into consideration would you like to give us a feedback on what are the specific needs that you have as a extension author?

**Comment by BojanKogoj** [comment]
@aminalhazwani If I may jump in:
- Copy/paste is not the worst idea for small, simple extensions but not ideal for something larger, especially since guidelines aren't even finished.
- Browser styles (using `chrome://`) sound good, but won't work if you want to support multiple browsers
- NPM module is in my opinion the best option

Since I'm making a new extension I already needed something similar to what is in this PR, so I made my own library using SASS (far from complete), which works well with the project (Angular 4 based extension).

**Comment by aminalhazwani** [comment]
sorry @BojanKogoj, more than welcome to jump in! Thanks for your feedback!

**Comment by vanillajonathan** [comment]
@aminalhazwani,

Depending on how the style sheet is distributed the class name can or cannot be changed.
- If distributed with the browser it cannot be changed as that would break the API.
- If distributed as a package it could be changed as long as versioned properly using semantic versioning. Then the extension only updated to a new version of the package when the extension has been updated to use the new class name.

When using another approach such as components, the same argument can be raised but instead of "You can never change a class name again" would be "You can never change a component name again". It boils down to changing the name of a reference does break the API.
Again it depends on how extension makes the reference, if its a reference from a file bundled with the extension or bundled with the browser.

In the second approach you list, do you mean things like [custom elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements) ([support](https://caniuse.com/#search=custom-elements)) such as:
```html
<messagebar type="success">Things went well.</messagebar>
```
Is that what you mean or do you mean something else?

If so, yes that would be an interesting approach and we should consider if that might be an better approach. I would be interested in this and feedback would be much appreciated.

If possible, please raise a discussion of desirable approaches and their pros/cons with the Firefox front-end developers and the Photon team. Collaboration, ideas and feedback is much appreciated.

## Needs as an extension author
As an extension author I have the need to style my extension so it adheres to design on the platform it runs on, in this case that would be the Photon Design System on Firefox. To make the extension feel as an extension of the browser it needs a consistent user interface.
So as an extension author I would set the`browser_style` property to `true` in my `manifest.json` file. When my extension opens a new tab that loads a HTML page bundled with the extension I would like to style that page. This I would do with a style sheet that I reference in the `<head>` of my page.

The style sheet included in this PR aims to be that style sheet.
So the extension would have a dependency on this style sheet.
The style sheet could either be included with the extension or shipped with the browser and referenced by the extension.
This style sheet in turn depends the `colors.css` file which could either be included with the style sheet or be shipped as part of the browser and referenced by the style sheet.

@BojanKogoj Thanks for jumping in. :)
As for multiple browser support, I am not sure you would want the extension to carry the Photon design on non-Mozilla browsers such as Chrome and Edge.

**Comment by flying-sheep** [comment]
Hi! There’s one thing that’s very important to me:

We don’t want to break compatibility again. We *just* introducted WebExtensions and `"browser_style": true`. Everything points to the “out of date” Firefox style guide.

As an addon author who wanted to bite the bullet and remade made his legacy addon, I’d have looked for how to make it look native. I’d have used [this](http://design.firefox.com/StyleGuide/#/navigation) and would definitely be sad and confused if this breaks *again*, mere months after it was introduced!

An addon containing a `.panel-section-tabs-button` should continue to look native and we shouldn’t replace `chrome://browser/content/extension.css` with something incompatible to what it currently is.

**Comment by vanillajonathan** [comment]
@flying-sheep The Photon Design is currently just a draft document, a style guide. No official style sheet exists yet.
This pull requests contains a style sheet developed for my needs as a WebExtension developer from reading the material published at Photon Design website.
Currently the document contains no component for tabs.

You might want to post on [bugzilla.mozilla.org](https://bugzilla.mozilla.org/) about updating `extension.css` with the style from Photon Design.

**Comment by flying-sheep** [comment]
Thanks, I did that by now: https://bugzil.la/1421652

**Comment by vanillajonathan** [comment]
@flying-sheep Good issue filed.
The `browser_style` preference only sets the style for the popup. It does not style pages opened up in new tabs. This CSS file allows you to set the style for pages opened up in new tabs.

**Comment by brassy-** [comment]
Please, let's move this discussion to this repo [photon-extension-kit](https://github.com/FirefoxUX/photon-extension-kit). We're using github to involve the community into the development of  `extensions.css` new version: a stylesheet for extensions' developers.

**Pull request closed without merging**
