### PR TITLE
Add purple 30 and 40, add changelog

### PR DESCRIPTION
**Pull request by aminalhazwani**
As requested by @ericawright I created two new purple shades: purple 30 `#c069ff` and purple 40 `#ad3bff`.

I also add a `CHANGELOG.md`

### CODE REVIEW

**Review by shorlander — COMMENTED** [review]
Looks good to me. Thanks!

**Review by bwinton — APPROVED** [review]
Should we bump the version number in package.json too?

**Comment by aminalhazwani** [comment]
@bwinton good catch, bumped version to 3.2.0

**Comment by aminalhazwani** [comment]
Ready for merge!

**Pull request merged**
