### PR TITLE
Add all the icons.

### PR DESCRIPTION
**Pull request by bwinton**

### CODE REVIEW

**Comment by aminalhazwani** [comment]
Cool, thanks @bwinton!

I have a couple of questions:
- Should the icon source file include the license even if it will be added later with the generating script? 
- Should we specify the `fill` property in the source file even if it will be added later with the generating script?
- Should we remove the sub folder from the path such as `/alert/`, `/permission/` since they are already specified in the JSON under the category? 

I will now cross check these icons with the ones that we have on Google Drive. If there are icons missing here can I add them to this PR?

**Comment by bwinton** [comment]
> Should the icon source file include the license even if it will be added later with the generating script?

I would say no, because it's covered under the license of the project, but maybe ask someone in Legal.

> Should we specify the fill property in the source file even if it will be added later with the generating script?

I don't think so.

> Should we remove the sub folder from the path such as /alert/, /per
mission/ since they are already specified in the JSON under the category?

Maybe, but they are nice to keep things a little organized.

> I will now cross check these icons with the ones that we have on Google Drive. If there are icons missing here can I add them to this PR?

Yes! 🙂

**Comment by aminalhazwani** [comment]
Hey @bwinton,

I finally manage to review the PR. Here some considerations:

- I removed the subfolders as an icon can be under multiple `categories` so that we don't have repeating SVGs in the repository
- I did not remove the `fill` property and the license from the SVG source files because the script should clean all the icons before converting them to specific format and sizes
- I fixed a couple of instances in the JSON where an icon was indicated as size `16` but it actually was size `12` or `24`
- I removed the `deprecated-` prefix from all the icons and left it only in the `categories` JSON property 
- I added a prefix `developer-` to the devtools icons as sometimes they are using names that are already taken - eg play, pause - naming for duplicates TBD

Other questions:

- Can the script reorder the JSON to list the icons alphabetically?
- Are we at a good point to bind this with the icons website?
- I added a `back` icon for iOS and Android, can we start to work on the conversion script? For Android you can touch base with Sebastian Kaspari and for iOS with Farhan Patel.
https://github.com/FirefoxUX/design-tokens/blob/5035a0aa286d73d2ddacd8c78e02b1722eb2938c/photon-icons/photon-icons.json#L1027-L1031

**Review by aminalhazwani — APPROVED** [review]
Beside the non-blocking questions listed above we can merge this and move the conversation forward

**Pull request merged**
