### PR TITLE
Fixes #32 - Add alpha channel to color tokens when needed

### LINKED ISSUE #32: Add alpha channel to color tokens when needed
This is an issue for opening a conversation around how to implement opaque colors in the color tokens. Will follow up with a couple of proposals tomorrow!

### PR DESCRIPTION
**Pull request by aminalhazwani**
I thought to open a work in progress PR so that we can track and discuss changes here ☺️

### CODE REVIEW

**Comment by aminalhazwani** [comment]
Ok, I tested the generated `photon-colors.sketchpalette` for Sketch.app and it works like a charm. It's nice that Sketch.app puts a little pattern behind transparent fills ☺️ 

screen shot 2017-12-19 at 2 38 20 pm

**Comment by aminalhazwani** [comment]
I also checked the `photon-colors.css` and I am wondering: is it clear enough to have the variable named like `--blue-50-30` or could/should we be more explicit and descriptive? Some ideas (I checked a couple of other design systems and MDN):

- `--blue-50-opacity-30`
- `--blue-50-transparent-30`
- `--blue-50-alpha-30`
- `--blue-50-alpha-channel-30`
- `--blue-50-alpha-value-30`

What do you think @bwinton? Would be nice to reach out also to the people who are currently using the module!

**Comment by vanillajonathan** [comment]
I like `--blue-50-opacity-30`.

**Comment by bwinton** [comment]
Eesh, those all seem really verbose to me…  :neutral_face:
What about `--blue-5-a30` or `--blue-50-a-30`?

**Comment by aminalhazwani** [comment]
Probably if you read `--blue-50-30: rgba(10, 132, 255, 0.3);` you could guess that the `30` is the alpha value. Maybe is less clear once we are going to use those values in the documentation. Eg in the [buttons page](https://design.firefox.com/photon/components/buttons.html#default-2) how could we specify the background color of a default button? Maybe once we implement the tokens in the documentation we could display all generated values with a little dropdown or segmented button. 

Personally I don't have a preference but I just wanted to be sure that we would consider all possible use scenarios.

**Comment by gasolin** [comment]
Material UI has some color code like `deep-purple-500-a100`
https://material.io/guidelines/style/color.html#color-color-palette

And here how they define the color code in (s)css
https://github.com/material-components/material-components-web/blob/master/packages/mdc-theme/_color-palette.scss

Haven't dig further to know if `-a100` means alpha/opacity %10 for `deep-purple-500` (they seems not add alpha for each color level). If `-a100` means alpha/opacity, we could follow the similar rule(`-a10`) so the developer could pick up between different design system with less confusion.

**Comment by aminalhazwani** [comment]
@gasolin thanks for your feedback! The `-a100` in the material color palette stands for "accent" and not for "alpha" so unfortunately if we would use that we were not following a similar rule. I don't see a strong improvement between using `--blue-50-30` and `--blue-50-a30` because in both cases we would have to explain what `30` or `a30` stand for. If all other option are too verbose for you folks let's keep the original `--blue-50-30` ☺️

**Comment by vanillajonathan** [comment]
It might not be too verbose depending on how commonly used the ones with opacity are used.
It is desirable for the most common ones to be short, but if opacity is rarely used then it might not matter if its a bit verbose.

**Comment by bwinton** [comment]
Let's go with `--blue-50-a30`, and I'll implement that…

**Comment by bwinton** [comment]
Okay, I think this is good. Anyone want to review it and make sure it's okay, or see what else we should add?

**Comment by aminalhazwani** [comment]
@bwinton I think we're missing the opaque colors for `.gpl` and `.soc`

**Comment by bwinton** [comment]
Yep. I don't have any spec for how `.gpl` or `.soc` files handle transparent colours, so I left them out. If you can send me samples, I can add them in! :)

**Comment by vanillajonathan** [comment]
I am not aware if `.gpl` or `.soc` files support transparent colors. They might not.

**Comment by aminalhazwani** [comment]
Ok @bwinton let's merge this PR, publish a new version and move this forward. If then @vanillajonathan you find a way to add transparency in `.gpl` and `.soc` let us know, thank you very much!

**Pull request merged**
