### PR TITLE
Generate OpenOffice/LibreOffice palette

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Review by bwinton — APPROVED** [review]
I have no idea if this works, but sure, let's go for it!

**Comment by vanillajonathan** [comment]
Can you build and commit it?

**Comment by bwinton** [comment]
Doing that now.

**Comment by bwinton** [comment]
And done.

**Comment by vanillajonathan** [comment]
It works for me, I tested it on LibreOffice version 5.4.1.2.

**Comment by vanillajonathan** [comment]
Since LibreOffice names the color palette after the file name, if the file is copied to `/usr/lib/libreoffice/share/palette/` as `colors.soc` then the palette in LibreOffice is named `colors`.

So it would be good if we named this file `photon.soc` or `firefox.soc` instead.

**Pull request merged**
